#ifndef UTIL_ERR_CODE_HPP
#define UTIL_ERR_CODE_HPP

const int FAILED_TO_CREATE = 1001;
const int INVALID_STATUS = 1002;
const int VALUE_NOT_FOUND = 1003;
const int PROCESS_RUNNING = 1004;
#endif // UTIL_ERR_CODE_HPP